### ISSUE TITLE
[Feature Request] Starred Plugin -> Star a Folder

### ISSUE THREAD

**Issue by FelipeRearden** [valentine195/obsidian-prominent-starred-files#1]
Hello @valentine195 !!!!

I have a FR that is related to Starred Plugin but not 100% related to this plugin. 
- Since this is the only plugin that enhance the Starred Plugin I decide to share with you my idea. 

**Feel free to discard and close this FR if you think it is something that don’t fit in this plugin :)**

My FR simple to explain: Add the ability to define `Folders` as stars (favorite) inside the Starred Plugin .   	

Thanks for reading this and I wish you a fantastic day

**Comment by red-co** [comment]
yes, it will be great

**Comment by FelipeRearden** [comment]
> yes, it will be great

Let's 🙏 for this feature and for @valentine195  !!!!!!!!

**Comment by red-co** [comment]
> 
I spent some time today, found a plugin that can do this thing, 😂,we probably don't need to do the star folder plugin, because breadcrumbs can do this function better, and it is in the md file, you can try it,

**Comment by red-co** [comment]
> > 
> 
> I spent some time today, found a plugin that can do this thing, 😂,we probably don't need to do the star folder plugin, because breadcrumbs can do this function better, and it is in the md file, you can try it,

just use YAML
---
BC-folder-note : down
---
